# https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863
name: Upload package to NuGet

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Upload package to NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore
        run: dotnet restore /property:Configuration=Release
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        
      - name: Build
        run: dotnet build -c Release --no-restore /p:Version=${VERSION} /p:PackageVersion=${VERSION}
      - name: Test
        run: dotnet test -c Release --no-restore --no-build
        
      - name: Pack
        run: dotnet pack -c Release /p:Version=${VERSION} --no-restore
        
      - name: Upload Bunkum.Core
        run: dotnet nuget push Bunkum.Core/bin/Release/Bunkum.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Upload Bunkum.ProfanityFilter
        run: dotnet nuget push Bunkum.ProfanityFilter/bin/Release/Bunkum.ProfanityFilter.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Upload Bunkum.RealmDatabase
        run: dotnet nuget push Bunkum.RealmDatabase/bin/Release/Bunkum.RealmDatabase.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Upload Bunkum.AutoDiscover
        run: dotnet nuget push Bunkum.AutoDiscover/bin/Release/Bunkum.AutoDiscover.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Upload Bunkum.HealthChecks
        run: dotnet nuget push Bunkum.HealthChecks/bin/Release/Bunkum.HealthChecks.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Upload Bunkum.Protocols.Http
        run: dotnet nuget push Bunkum.Protocols.Http/bin/Release/Bunkum.Protocols.Http.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Upload Bunkum.Protocols.Gopher
        run: dotnet nuget push Bunkum.Protocols.Gopher/bin/Release/Bunkum.Protocols.Gopher.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Upload Bunkum.Listener
        run: dotnet nuget push Bunkum.Listener/bin/Release/Bunkum.Listener.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
            NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}